Remove free brains and bones
jamesmgittins/incremancer pull request #9
Opened 2020-04-11 07:35 UTC by plasticmacaroni

By upgrading brains and bones rates (but not blood rate for blood?) players received free brains and bones every tick. 

This just removes those two lines, but leaves increased income rate upgrades intact.

2020-11-28 13:21 UTC, petertseng requested changes
These changes shouldn't be applied. bonesRate and brainsRate are the trophies that confer bones and brains per second. Removing these lines would make those trophies inoperational.

The prestige upgrades that increase bone and brain income are bonesGainPC and brainsGainPC.

2020-11-29 20:43 UTC, plasticmacaroni commented
I'm afraid I don't understand. brainsRate and bonesRate are the resource income rate multipliers. There may be associated trophies, but that check happens elsewhere from what I can tell. 

Removing this line and testing removed the free resources applied every tick for me. If there were other side effects let me know what else occured for you and I'm happy to revise. 

It's also been 8 months pending for this PR, so I doubt it will be applied.

2020-11-30 00:12 UTC, petertseng commented
> I'm afraid I don't understand. brainsRate and bonesRate are the resource income rate multipliers

Yes, I think I've misunderstood you too. I thought these two are the resource income rate multipliers you are referring to:

https://github.com/jamesmgittins/incremancer/blob/0b921f429dc928529e43ed634049936c1e277087/js/upgrades.js#L1039-L1040

And I thought these are trophies:

https://github.com/jamesmgittins/incremancer/blob/0b921f429dc928529e43ed634049936c1e277087/js/trophies.js#L32-L33

https://github.com/jamesmgittins/incremancer/blob/0b921f429dc928529e43ed634049936c1e277087/js/trophies.js#L41-L42

Please let me know where I went wrong so we can get on the same page and reach an understanding

2020-11-30 00:44 UTC, jamesmgittins commented
The ones in the commit for this pull request are the trophies that give passive income. It's already working as intended.

If you look in upgrades.js at the arrays at the bottom of the file you'll see there are no purchasable upgrades for brainsRate or bonesRate. The only way to get those upgrades is through the trophies in trophies.js.

2020-11-30 00:44 UTC, closed without merging